services:
  # --- Base de Datos MySQL ---
  mysql-db:
    image: mysql:8.0
    container_name: transfers-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: transfers_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: miguel_user
      MYSQL_PASSWORD: miguel_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  #LINEA PARA QUE CREE LA TABLA DEL MYSQL

  # --- Servidor de Mensajería ---
  rabbitmq: # <--- Ahora está alineado con los demás servicios
    image: rabbitmq:3-management
    container_name: transfers-rabbitmq
    restart: always
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Dashboard
    environment:
      - RABBITMQ_DEFAULT_USER=miguel_rabbit
      - RABBITMQ_DEFAULT_PASS=miguel_rabbit
    volumes:
      - rabbit_data:/var/lib/rabbitmq

  # --- Tu Aplicación en Go ---
  app:
    image: transfers-api:0.1.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: transfers-api
    depends_on:
      - mysql-db
      - rabbitmq
    ports:
      - "8080:8080"
    environment:
      # ---- Business ----
      TRANSFER_MIN_AMOUNT: 1

      # ---- MySQL Config ----
      DB_SOURCE: "miguel_user:miguel_password@tcp(mysql-db:3306)/transfers_db?parseTime=true"
      
      # ---- RabbitMQ Config ----
      # Esta es la URL que usará amqp.Dial() en tu código
      RABBITMQ_URL: "amqp://miguel_rabbit:miguel_rabbit@rabbitmq:5672/"
    restart: always

volumes:
  mysql_data:
  rabbit_data: