
services:
  # --- Base de Datos MySQL ---
  mysql-db:
    image: mysql:8.0
    container_name: transfers-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: transfers_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: miguel_user
      MYSQL_PASSWORD: miguel_password
    volumes:
      - mysql_data:/var/lib/mysql

  # --- Tu Aplicación en Go ---
  app:
    image: transfers-api:0.1.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: transfers-api
    depends_on:
      - mysql-db
    ports:
      - "8080:8080"
    environment:
      # ---- Business ----
      TRANSFER_MIN_AMOUNT: 1

      # ---- MySQL Config para Go ----
      DB_HOST: mysql-db
      DB_PORT: 3306
      DB_USER: miguel_user
      DB_PASSWORD: miguel_password
      DB_NAME: transfers_db
      # Cadena de conexión que leerá tu main.go
      DB_SOURCE: "miguel_user:miguel_password@tcp(mysql-db:3306)/transfers_db?parseTime=true"
    restart: always

volumes:
  mysql_data: