// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "transfers-api/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Create provides a mock function with given fields: t
func (_m *Repository) Create(t *models.Transfer) error {
	ret := _m.Called(t)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Transfer) error); ok {
		r0 = rf(t)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *Repository) Delete(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: id
func (_m *Repository) GetByID(id string) (*models.Transfer, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.Transfer
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.Transfer, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *models.Transfer); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Transfer)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBySenderID provides a mock function with given fields: senderID
func (_m *Repository) GetBySenderID(senderID string) ([]*models.Transfer, error) {
	ret := _m.Called(senderID)

	if len(ret) == 0 {
		panic("no return value specified for GetBySenderID")
	}

	var r0 []*models.Transfer
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]*models.Transfer, error)); ok {
		return rf(senderID)
	}
	if rf, ok := ret.Get(0).(func(string) []*models.Transfer); ok {
		r0 = rf(senderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Transfer)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(senderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with no fields
func (_m *Repository) List() ([]*models.Transfer, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*models.Transfer
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*models.Transfer, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*models.Transfer); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Transfer)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: t
func (_m *Repository) Update(t *models.Transfer) error {
	ret := _m.Called(t)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.Transfer) error); ok {
		r0 = rf(t)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
